### ISSUE TITLE
[Booru] NSFW in SFW channels E621 loophole.

### ISSUE THREAD

**Issue by RichyG93** [Jintaku/Jintaku-Cogs-V3#13]
This cog will check if `rating:questionable` or `rating:explicit` is used in SFW channels, and deny the search. However, some sites use shortened ratings like `rating:q` or `rating:e` which are not detected by the cog, and thus show NSFW content in SFW channels. Furthermore, it seems like the filter doesn't accept ratings. Trying to filter `rating:e` seems to do nothing.

E621 is an example of a booru that uses shortened rating tags.

**Comment by lionirdeadman** [comment]
Aw crap, that seems pretty serious, I'll install Red again to investigate and fix the issue.
