### ISSUE TITLE
E621 API Change

### ISSUE THREAD

**Issue by TwinDragon** [Jintaku/Jintaku-Cogs-V3#23]
This is a fairly quick fix that can be done, but a couple months ago, E621 had changed their API URL to the following:
`https://e621.net/posts.json?limit=320&tags=`

Currently in the code, it'll always fail to return a result.

**Comment by lionirdeadman** [comment]
Hmmm, that's an easy fix but we also need to fix #13 which I think was a story of `rating:e` vs `rating:explicit` and the such so for now, it might actually be better to keep it broken until that's fixed.

**Comment by TwinDragon** [comment]
Ah right, I did see that issue. That'd be a good idea in the meantime until that one is fixed.
