### ISSUE TITLE
[Wikia] Setting to switch between thumbnail area and embed image area and bigger text description

### ISSUE THREAD

**Issue by owocado** [Jintaku/Jintaku-Cogs-V3#24]
Hi,

So as we discussed in DMs on discord, I have 2 feature request for wikia cog. One would be to have it display more text in description area and 2nd would be to shift the article pic from the thumbnail area to embed image area so it looks bigger and more clear to see from mobile devices.

**Comment by lionirdeadman** [comment]
Note : Should use Red's setting API rather than Config too

**Comment by lionirdeadman** [comment]
Related to #29
