### ISSUE TITLE
[ERROR][BOORU] pussy command throws error

### ISSUE THREAD

**Issue by Element21** [Jintaku/Jintaku-Cogs-V3#41]
Error in command 'pussy'. Check your console or logs for details.
Logs:
![booru](https://user-images.githubusercontent.com/36175783/95689347-118c8880-0bde-11eb-8472-95f47985b113.png)

**Comment by lionirdeadman** [comment]
Seems I removed the code which made that command work. I'm not sure when. I'll remove the command then.

**Comment by Element21** [comment]
No problem!

**Comment by lionirdeadman** [comment]
I didn't fix it yet so I'll keep it open
